version: "3"

services:
    front:
        image: nginx:1.11
        ports:
            - 127.0.0.1:48100:80
            - 127.0.0.1:48101:443
        volumes:
            - ./:/home/docker:ro
            - ./docker/front/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./docker/front/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./docker/front/ssl.crt:/etc/nginx/ssl.crt:ro
            - ./docker/front/ssl.csr:/etc/nginx/ssl.csr:ro
            - ./docker/front/ssl.key:/etc/nginx/ssl.key:ro
        working_dir: /etc/nginx
        depends_on: [engine]
        labels: 
            - "traefik.frontend.rule=Host:symfony.local"
            - "traefik.port=443"
            - "traefik.protocol=https"
        networks: { default: { aliases: ['symfony.local']}}

    engine:
        build:
            context: ./
            dockerfile: ./docker/engine/Dockerfile
            args:
                BUILD_ENV: dev
        environment:
            COMPOSER_HOME: /usr/local/bin
        ports:
            - 127.0.0.1:48110:9000
        user: "1000"
        volumes:
            - ./docker/engine/php.ini:/usr/local/etc/php/conf.d/custom.ini:ro
            - ./:/home/docker:rw
        working_dir: /home/docker
        depends_on: ["db"]

    db:
        image: postgres:10.3
        environment:
            - POSTGRES_PASSWORD=symfony
            - POSTGRES_USER=symfony
            - POSTGRES_DB=symfony
        ports:
            - 127.0.0.1:48120:5432
        volumes:
            - db:/var/lib/postgresql/data
        working_dir: /home/docker

    build:
        image: node:10
        volumes:
            - ./:/home/docker
        working_dir: /home/docker

    maildev:
        image: djfarrelly/maildev
        ports:
            - 127.0.0.1:48150:25
            - 127.0.0.1:48151:80
        depends_on: [engine]
        labels: 
            - "traefik.frontend.rule=Host:mail.symfony.local"
            - "traefik.port=80"
        networks: { default: { aliases: ['mail.symfony.local']}}

    pgadmin:
        image: fenglc/pgadmin4:2.1
        ports:
            - 127.0.0.1:48160:5050
        volumes:
            - pgadmin:/var/lib/pgadmin/
        labels: ["traefik.frontend.rule=Host:database.symfony.local"]
        depends_on: [db]
        networks: { default: { aliases: ['database.symfony.local']}}

volumes:
    db: {}
    pgadmin: {}
    mongo: {}
    redis: {}
